clear; close all; clc;
data = {'Urgent'	'Yes'	'Yes';
	'Urgent'	'No'	'Yes';
	'Near'		'Yes'	'Yes';
	'None'		'Yes'	'No';
	'None'		'No'	'Yes';
	'None'		'Yes'	'No';
	'Near'		'No'	'No';
	'Near'		'No'	'Yes';
	'Near'		'Yes'	'Yes';
	'Urgent'	'No'	'Yes'};
labels = {	'Party'
		'Study';
		'Party';
		'Party';
		'Pub';
		'Party';
		'Study';
		'TV';
		'Party';
		'Study'};
data = [1 1 1; 
	1 2 1; 
	2 1 1; 
	3 1 2; 
	3 2 1; 
	3 1 2; 
	2 2 2; 
	2 2 1; 
	2 1 1;
	1 2 1];
labels = [	1;
		2;
		1;
		1;
		3;
		1;
		2;
		4;
		1;
		2];

featureNames = {'Deadline', 'Party', 'Lazy'};
tree = Make_Tree_ID3(data, labels, featureNames);
